export const SET_MESSAGE = "SET_MESSAGE";
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
